In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df1 = pd.read_csv(r"E:\EYE DATASET\Training_Labels.csv")
df1

,ID,Disease_Risk,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1915,1916,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1916,1917,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1917,1918,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1918,1919,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1919,1920,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
import os
import random
import cv2
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("full_df.csv")
df

,ID,Patient Age,Patient Sex,Left-Fundus,Right-Fundus,Left-Diagnostic Keywords,Right-Diagnostic Keywords,N,D,G,C,A,H,M,O,filepath,labels,target,filename
0,0,69,Female,0_left.jpg,0_right.jpg,cataract,normal fundus,0,0,0,1,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['N'],"[1, 0, 0, 0, 0, 0, 0, 0]",0_right.jpg
1,1,57,Male,1_left.jpg,1_right.jpg,normal fundus,normal fundus,1,0,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['N'],"[1, 0, 0, 0, 0, 0, 0, 0]",1_right.jpg
2,2,42,Male,2_left.jpg,2_right.jpg,laser spotï¼Œmoderate non proliferative retinopathy,moderate non proliferative retinopathy,0,1,0,0,0,0,0,1,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",2_right.jpg
3,4,53,Male,4_left.jpg,4_right.jpg,macular epiretinal membrane,mild nonproliferative retinopathy,0,1,0,0,0,0,0,1,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4_right.jpg
4,5,50,Female,5_left.jpg,5_right.jpg,moderate non proliferative retinopathy,moderate non proliferative retinopathy,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",5_right.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6387,4686,63,Male,4686_left.jpg,4686_right.jpg,severe nonproliferative retinopathy,proliferative diabetic retinopathy,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4686_left.jpg
6388,4688,42,Male,4688_left.jpg,4688_right.jpg,moderate non proliferative retinopathy,moderate non proliferative retinopathy,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4688_left.jpg
6389,4689,54,Male,4689_left.jpg,4689_right.jpg,mild nonproliferative retinopathy,normal fundus,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4689_left.jpg
6390,4690,57,Male,4690_left.jpg,4690_right.jpg,mild nonproliferative retinopathy,mild nonproliferative retinopathy,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4690_left.jpg
6391,4784,58,Male,4784_left.jpg,4784_right.jpg,hypertensive retinopathyï¼Œage-related macular d...,hypertensive retinopathyï¼Œage-related macular d...,0,0,0,0,1,1,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['H'],"[0, 0, 0, 0, 0, 1, 0, 0]",4784_left.jpg

In [5]:
col = df1.columns
len(col)

47

In [6]:
a = {}
for i in range(1920):
    for j in range(1,47):
        if(df1['Disease_Risk'][i] == 1):
            if(df1[col[j]][i] == 1 and df1[col[j]][i] != 'Disease_Risk'):
                a[i] = col[j]
        else:
            a[i] = 0

In [7]:
a[0]

'DR'

In [8]:
for i in range(len(a)):
    if(a[i] != 'DR' and a[i]!='ARMD' and a[i]!='MYA'):
        del a[i]

In [9]:
len(a)

345

In [10]:
count=0
DR = []
ARMD = []
MYA = []
NOR = []
for key,value in a.items():
    if(value=='MYA'):
        MYA.append(key)
    if(value == 'DR'):
        DR.append(key)
    if(value=='ARMD'):
        ARMD.append(key)

In [11]:
print(len(DR))
print(len(ARMD))
print(len(MYA))
print(len(NOR))

240
34
71
0

In [12]:
img_dir1 = r'E:\EYE DATASET\Training Dataset'

In [13]:
df_DR_filenames = pd.DataFrame(DR,columns=['filenames'])

In [14]:
df_DR_filenames['labels'] = "DR"

In [15]:
df_DR_filenames

     filenames labels
0            0     DR
1            1     DR
2            2     DR
3           19     DR
4           35     DR
..         ...    ...
235       1668     DR
236       1680     DR
237       1681     DR
238       1686     DR
239       1692     DR

[240 rows x 2 columns]

In [16]:
for i in range(len(df_DR_filenames['filenames'])):
    df_DR_filenames['filenames'][i] = df_DR_filenames['filenames'][i]+1

<ipython-input-16-de2a1b5ec921>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_DR_filenames['filenames'][i] = df_DR_filenames['filenames'][i]+1

In [17]:
df_DR_filenames

     filenames labels
0            1     DR
1            2     DR
2            3     DR
3           20     DR
4           36     DR
..         ...    ...
235       1669     DR
236       1681     DR
237       1682     DR
238       1687     DR
239       1693     DR

[240 rows x 2 columns]

In [18]:
x = []
for i in range(240):
    x.append(str(df_DR_filenames['filenames'][i]))

In [19]:
df_DR_filenames['filenames'] = x

In [20]:
x = []
for i in range(len(df_DR_filenames['filenames'])):
    x.append(df_DR_filenames['filenames'][i] + '.png')

In [21]:
df_DR_filenames['filenames'] = x

In [22]:
df_DR_filenames

    filenames labels
0       1.png     DR
1       2.png     DR
2       3.png     DR
3      20.png     DR
4      36.png     DR
..        ...    ...
235  1669.png     DR
236  1681.png     DR
237  1682.png     DR
238  1687.png     DR
239  1693.png     DR

[240 rows x 2 columns]

In [23]:
df_ARMD_filenames = pd.DataFrame(data = ARMD,columns = ['filenames'])

In [24]:
df_ARMD_filenames

    filenames
0          24
1         141
2         203
3         456
4         460
5         525
6         546
7         688
8         730
9         754
10        755
11        877
12       1049
13       1190
14       1191
15       1217
16       1229
17       1268
18       1269
19       1286
20       1327
21       1343
22       1539
23       1551
24       1555
25       1556
26       1579
27       1580
28       1591
29       1598
30       1599
31       1604
32       1677
33       1691

In [25]:
for i in range(len(df_ARMD_filenames['filenames'])):
    df_ARMD_filenames['filenames'][i] = df_ARMD_filenames['filenames'][i] + 1

In [26]:
df_ARMD_filenames['filenames']

0       25
1      142
2      204
3      457
4      461
5      526
6      547
7      689
8      731
9      755
10     756
11     878
12    1050
13    1191
14    1192
15    1218
16    1230
17    1269
18    1270
19    1287
20    1328
21    1344
22    1540
23    1552
24    1556
25    1557
26    1580
27    1581
28    1592
29    1599
30    1600
31    1605
32    1678
33    1692
Name: filenames, dtype: int64

In [27]:
x = []
for i in range(len(df_ARMD_filenames)):
    x.append(str(df_ARMD_filenames['filenames'][i]))

In [28]:
df_ARMD_filenames['filenames'] = x

In [29]:
df_ARMD_filenames['filenames'] = x

In [30]:
x

['25',
 '142',
 '204',
 '457',
 '461',
 '526',
 '547',
 '689',
 '731',
 '755',
 '756',
 '878',
 '1050',
 '1191',
 '1192',
 '1218',
 '1230',
 '1269',
 '1270',
 '1287',
 '1328',
 '1344',
 '1540',
 '1552',
 '1556',
 '1557',
 '1580',
 '1581',
 '1592',
 '1599',
 '1600',
 '1605',
 '1678',
 '1692']

In [31]:
df_ARMD_filenames['labels'] = 'ARMD'

In [32]:
df_ARMD_filenames

   filenames labels
0         25   ARMD
1        142   ARMD
2        204   ARMD
3        457   ARMD
4        461   ARMD
5        526   ARMD
6        547   ARMD
7        689   ARMD
8        731   ARMD
9        755   ARMD
10       756   ARMD
11       878   ARMD
12      1050   ARMD
13      1191   ARMD
14      1192   ARMD
15      1218   ARMD
16      1230   ARMD
17      1269   ARMD
18      1270   ARMD
19      1287   ARMD
20      1328   ARMD
21      1344   ARMD
22      1540   ARMD
23      1552   ARMD
24      1556   ARMD
25      1557   ARMD
26      1580   ARMD
27      1581   ARMD
28      1592   ARMD
29      1599   ARMD
30      1600   ARMD
31      1605   ARMD
32      1678   ARMD
33      1692   ARMD

In [33]:
df_MYA_filenames = pd.DataFrame(data = MYA,columns = ['filenames'])

In [34]:
for i in range(len(df_MYA_filenames['filenames'])):
    df_MYA_filenames['filenames'][i] = df_MYA_filenames['filenames'][i] + 1

In [35]:
x = []
for i in range(len(df_MYA_filenames['filenames'])):
    x.append(str(df_MYA_filenames['filenames'][i]))

In [36]:
df_MYA_filenames['filenames'] = x

In [37]:
df_MYA_filenames['labels'] = 'Myopia'

In [38]:
df_MYA_filenames

   filenames  labels
0          6  Myopia
1          7  Myopia
2          8  Myopia
3        107  Myopia
4        108  Myopia
..       ...     ...
66      1713  Myopia
67      1722  Myopia
68      1723  Myopia
69      1851  Myopia
70      1866  Myopia

[71 rows x 2 columns]

In [39]:
x = []
for i in range(len(df_MYA_filenames['filenames'])):
    x.append(df_MYA_filenames['filenames'][i] + '.png')

In [40]:
df_MYA_filenames['filenames'] = x

In [41]:
df_MYA_filenames

   filenames  labels
0      6.png  Myopia
1      7.png  Myopia
2      8.png  Myopia
3    107.png  Myopia
4    108.png  Myopia
..       ...     ...
66  1713.png  Myopia
67  1722.png  Myopia
68  1723.png  Myopia
69  1851.png  Myopia
70  1866.png  Myopia

[71 rows x 2 columns]

In [42]:
df_combined1 = df_DR_filenames.append([df_ARMD_filenames,df_MYA_filenames],ignore_index = True)
df_combined1 = df_combined1.sample(345)

In [43]:
df_combined1 = df_combined1.sample(345)
df_combined1 = df_combined1.reset_index(drop=True)
df_combined1

    filenames  labels
0    1157.png      DR
1     106.png      DR
2     367.png      DR
3      62.png      DR
4    1232.png      DR
..        ...     ...
340  1356.png      DR
341  1252.png      DR
342   705.png      DR
343      1557    ARMD
344  1031.png  Myopia

[345 rows x 2 columns]

In [44]:
a  = np.array(df_combined1.filenames)
paths = []
type(paths)

list

In [45]:
img_dir1

'E:\\EYE DATASET\\Training Dataset'

In [46]:
for i in range(345):
    img = a[i]
    image = os.path.join(img_dir1, img)
    paths.append(image)

In [47]:
paths

['E:\\EYE DATASET\\Training Dataset\\1157.png',
 'E:\\EYE DATASET\\Training Dataset\\106.png',
 'E:\\EYE DATASET\\Training Dataset\\367.png',
 'E:\\EYE DATASET\\Training Dataset\\62.png',
 'E:\\EYE DATASET\\Training Dataset\\1232.png',
 'E:\\EYE DATASET\\Training Dataset\\1330.png',
 'E:\\EYE DATASET\\Training Dataset\\1021.png',
 'E:\\EYE DATASET\\Training Dataset\\1121.png',
 'E:\\EYE DATASET\\Training Dataset\\1518.png',
 'E:\\EYE DATASET\\Training Dataset\\8.png',
 'E:\\EYE DATASET\\Training Dataset\\827.png',
 'E:\\EYE DATASET\\Training Dataset\\1396.png',
 'E:\\EYE DATASET\\Training Dataset\\739.png',
 'E:\\EYE DATASET\\Training Dataset\\584.png',
 'E:\\EYE DATASET\\Training Dataset\\44.png',
 'E:\\EYE DATASET\\Training Dataset\\772.png',
 'E:\\EYE DATASET\\Training Dataset\\1062.png',
 'E:\\EYE DATASET\\Training Dataset\\111.png',
 'E:\\EYE DATASET\\Training Dataset\\1523.png',
 'E:\\EYE DATASET\\Training Dataset\\967.png',
 'E:\\EYE DATASET\\Training Dataset\\1084.png',
 'E:\\EYE DATASET\\Training Dataset\\1413.png',
 'E:\\EYE DATASET\\Training Dataset\\246.png',
 'E:\\EYE DATASET\\Training Dataset\\468.png',
 'E:\\EYE DATASET\\Training Dataset\\1593.png',
 'E:\\EYE DATASET\\Training Dataset\\144.png',
 'E:\\EYE DATASET\\Training Dataset\\1380.png',
 'E:\\EYE DATASET\\Training Dataset\\98.png',
 'E:\\EYE DATASET\\Training Dataset\\1036.png',
 'E:\\EYE DATASET\\Training Dataset\\1322.png',
 'E:\\EYE DATASET\\Training Dataset\\7.png',
 'E:\\EYE DATASET\\Training Dataset\\1165.png',
 'E:\\EYE DATASET\\Training Dataset\\1642.png',
 'E:\\EYE DATASET\\Training Dataset\\39.png',
 'E:\\EYE DATASET\\Training Dataset\\615.png',
 'E:\\EYE DATASET\\Training Dataset\\613.png',
 'E:\\EYE DATASET\\Training Dataset\\1723.png',
 'E:\\EYE DATASET\\Training Dataset\\1389.png',
 'E:\\EYE DATASET\\Training Dataset\\1037.png',
 'E:\\EYE DATASET\\Training Dataset\\120.png',
 'E:\\EYE DATASET\\Training Dataset\\1542.png',
 'E:\\EYE DATASET\\Training Dataset\\1222.png',
 'E:\\EYE DATASET\\Training Dataset\\263.png',
 'E:\\EYE DATASET\\Training Dataset\\1395.png',
 'E:\\EYE DATASET\\Training Dataset\\1602.png',
 'E:\\EYE DATASET\\Training Dataset\\1552',
 'E:\\EYE DATASET\\Training Dataset\\479.png',
 'E:\\EYE DATASET\\Training Dataset\\1581',
 'E:\\EYE DATASET\\Training Dataset\\585.png',
 'E:\\EYE DATASET\\Training Dataset\\547',
 'E:\\EYE DATASET\\Training Dataset\\64.png',
 'E:\\EYE DATASET\\Training Dataset\\1313.png',
 'E:\\EYE DATASET\\Training Dataset\\918.png',
 'E:\\EYE DATASET\\Training Dataset\\1133.png',
 'E:\\EYE DATASET\\Training Dataset\\86.png',
 'E:\\EYE DATASET\\Training Dataset\\1065.png',
 'E:\\EYE DATASET\\Training Dataset\\1192',
 'E:\\EYE DATASET\\Training Dataset\\1866.png',
 'E:\\EYE DATASET\\Training Dataset\\756',
 'E:\\EYE DATASET\\Training Dataset\\773.png',
 'E:\\EYE DATASET\\Training Dataset\\1172.png',
 'E:\\EYE DATASET\\Training Dataset\\760.png',
 'E:\\EYE DATASET\\Training Dataset\\1223.png',
 'E:\\EYE DATASET\\Training Dataset\\20.png',
 'E:\\EYE DATASET\\Training Dataset\\1445.png',
 'E:\\EYE DATASET\\Training Dataset\\101.png',
 'E:\\EYE DATASET\\Training Dataset\\1061.png',
 'E:\\EYE DATASET\\Training Dataset\\1154.png',
 'E:\\EYE DATASET\\Training Dataset\\1447.png',
 'E:\\EYE DATASET\\Training Dataset\\1393.png',
 'E:\\EYE DATASET\\Training Dataset\\1050',
 'E:\\EYE DATASET\\Training Dataset\\1181.png',
 'E:\\EYE DATASET\\Training Dataset\\1514.png',
 'E:\\EYE DATASET\\Training Dataset\\306.png',
 'E:\\EYE DATASET\\Training Dataset\\1375.png',
 'E:\\EYE DATASET\\Training Dataset\\1673.png',
 'E:\\EYE DATASET\\Training Dataset\\1612.png',
 'E:\\EYE DATASET\\Training Dataset\\1534.png',
 'E:\\EYE DATASET\\Training Dataset\\346.png',
 'E:\\EYE DATASET\\Training Dataset\\1070.png',
 'E:\\EYE DATASET\\Training Dataset\\1533.png',
 'E:\\EYE DATASET\\Training Dataset\\1660.png',
 'E:\\EYE DATASET\\Training Dataset\\1682.png',
 'E:\\EYE DATASET\\Training Dataset\\305.png',
 'E:\\EYE DATASET\\Training Dataset\\2.png',
 'E:\\EYE DATASET\\Training Dataset\\1664.png',
 'E:\\EYE DATASET\\Training Dataset\\591.png',
 'E:\\EYE DATASET\\Training Dataset\\392.png',
 'E:\\EYE DATASET\\Training Dataset\\1665.png',
 'E:\\EYE DATASET\\Training Dataset\\1702.png',
 'E:\\EYE DATASET\\Training Dataset\\1358.png',
 'E:\\EYE DATASET\\Training Dataset\\1212.png',
 'E:\\EYE DATASET\\Training Dataset\\1639.png',
 'E:\\EYE DATASET\\Training Dataset\\343.png',
 'E:\\EYE DATASET\\Training Dataset\\541.png',
 'E:\\EYE DATASET\\Training Dataset\\1332.png',
 'E:\\EYE DATASET\\Training Dataset\\564.png',
 'E:\\EYE DATASET\\Training Dataset\\402.png',
 'E:\\EYE DATASET\\Training Dataset\\1600',
 'E:\\EYE DATASET\\Training Dataset\\457',
 'E:\\EYE DATASET\\Training Dataset\\1357.png',
 'E:\\EYE DATASET\\Training Dataset\\1103.png',
 'E:\\EYE DATASET\\Training Dataset\\204',
 'E:\\EYE DATASET\\Training Dataset\\61.png',
 'E:\\EYE DATASET\\Training Dataset\\1609.png',
 'E:\\EYE DATASET\\Training Dataset\\823.png',
 'E:\\EYE DATASET\\Training Dataset\\695.png',
 'E:\\EYE DATASET\\Training Dataset\\1713.png',
 'E:\\EYE DATASET\\Training Dataset\\485.png',
 'E:\\EYE DATASET\\Training Dataset\\1537.png',
 'E:\\EYE DATASET\\Training Dataset\\1520.png',
 'E:\\EYE DATASET\\Training Dataset\\1117.png',
 'E:\\EYE DATASET\\Training Dataset\\37.png',
 'E:\\EYE DATASET\\Training Dataset\\1582.png',
 'E:\\EYE DATASET\\Training Dataset\\50.png',
 'E:\\EYE DATASET\\Training Dataset\\759.png',
 'E:\\EYE DATASET\\Training Dataset\\1394.png',
 'E:\\EYE DATASET\\Training Dataset\\340.png',
 'E:\\EYE DATASET\\Training Dataset\\253.png',
 'E:\\EYE DATASET\\Training Dataset\\1026.png',
 'E:\\EYE DATASET\\Training Dataset\\828.png',
 'E:\\EYE DATASET\\Training Dataset\\1013.png',
 'E:\\EYE DATASET\\Training Dataset\\1619.png',
 'E:\\EYE DATASET\\Training Dataset\\1610.png',
 'E:\\EYE DATASET\\Training Dataset\\38.png',
 'E:\\EYE DATASET\\Training Dataset\\1171.png',
 'E:\\EYE DATASET\\Training Dataset\\1409.png',
 'E:\\EYE DATASET\\Training Dataset\\1628.png',
 'E:\\EYE DATASET\\Training Dataset\\1379.png',
 'E:\\EYE DATASET\\Training Dataset\\523.png',
 'E:\\EYE DATASET\\Training Dataset\\1626.png',
 'E:\\EYE DATASET\\Training Dataset\\1275.png',
 'E:\\EYE DATASET\\Training Dataset\\1712.png',
 'E:\\EYE DATASET\\Training Dataset\\1594.png',
 'E:\\EYE DATASET\\Training Dataset\\1420.png',
 'E:\\EYE DATASET\\Training Dataset\\1025.png',
 'E:\\EYE DATASET\\Training Dataset\\1368.png',
 'E:\\EYE DATASET\\Training Dataset\\1669.png',
 'E:\\EYE DATASET\\Training Dataset\\337.png',
 'E:\\EYE DATASET\\Training Dataset\\950.png',
 'E:\\EYE DATASET\\Training Dataset\\595.png',
 'E:\\EYE DATASET\\Training Dataset\\1408.png',
 'E:\\EYE DATASET\\Training Dataset\\393.png',
 'E:\\EYE DATASET\\Training Dataset\\1344',
 'E:\\EYE DATASET\\Training Dataset\\1.png',
 'E:\\EYE DATASET\\Training Dataset\\1417.png',
 'E:\\EYE DATASET\\Training Dataset\\1378.png',
 'E:\\EYE DATASET\\Training Dataset\\1060.png',
 'E:\\EYE DATASET\\Training Dataset\\1257.png',
 'E:\\EYE DATASET\\Training Dataset\\224.png',
 'E:\\EYE DATASET\\Training Dataset\\277.png',
 'E:\\EYE DATASET\\Training Dataset\\1666.png',
 'E:\\EYE DATASET\\Training Dataset\\228.png',
 'E:\\EYE DATASET\\Training Dataset\\1500.png',
 'E:\\EYE DATASET\\Training Dataset\\347.png',
 'E:\\EYE DATASET\\Training Dataset\\1349.png',
 'E:\\EYE DATASET\\Training Dataset\\1546.png',
 'E:\\EYE DATASET\\Training Dataset\\1541.png',
 'E:\\EYE DATASET\\Training Dataset\\538.png',
 'E:\\EYE DATASET\\Training Dataset\\1661.png',
 'E:\\EYE DATASET\\Training Dataset\\540.png',
 'E:\\EYE DATASET\\Training Dataset\\1415.png',
 'E:\\EYE DATASET\\Training Dataset\\1333.png',
 'E:\\EYE DATASET\\Training Dataset\\1398.png',
 'E:\\EYE DATASET\\Training Dataset\\1570.png',
 'E:\\EYE DATASET\\Training Dataset\\6.png',
 'E:\\EYE DATASET\\Training Dataset\\1692',
 'E:\\EYE DATASET\\Training Dataset\\49.png',
 'E:\\EYE DATASET\\Training Dataset\\1240.png',
 'E:\\EYE DATASET\\Training Dataset\\395.png',
 'E:\\EYE DATASET\\Training Dataset\\1414.png',
 'E:\\EYE DATASET\\Training Dataset\\1270',
 'E:\\EYE DATASET\\Training Dataset\\1678',
 'E:\\EYE DATASET\\Training Dataset\\1241.png',
 'E:\\EYE DATASET\\Training Dataset\\614.png',
 'E:\\EYE DATASET\\Training Dataset\\1616.png',
 'E:\\EYE DATASET\\Training Dataset\\1416.png',
 'E:\\EYE DATASET\\Training Dataset\\1441.png',
 'E:\\EYE DATASET\\Training Dataset\\616.png',
 'E:\\EYE DATASET\\Training Dataset\\1297.png',
 'E:\\EYE DATASET\\Training Dataset\\214.png',
 'E:\\EYE DATASET\\Training Dataset\\1667.png',
 'E:\\EYE DATASET\\Training Dataset\\108.png',
 'E:\\EYE DATASET\\Training Dataset\\1337.png',
 'E:\\EYE DATASET\\Training Dataset\\1687.png',
 'E:\\EYE DATASET\\Training Dataset\\1421.png',
 'E:\\EYE DATASET\\Training Dataset\\1722.png',
 'E:\\EYE DATASET\\Training Dataset\\1672.png',
 'E:\\EYE DATASET\\Training Dataset\\1039.png',
 'E:\\EYE DATASET\\Training Dataset\\1230',
 'E:\\EYE DATASET\\Training Dataset\\1211.png',
 'E:\\EYE DATASET\\Training Dataset\\1637.png',
 'E:\\EYE DATASET\\Training Dataset\\1309.png',
 'E:\\EYE DATASET\\Training Dataset\\1655.png',
 'E:\\EYE DATASET\\Training Dataset\\241.png',
 'E:\\EYE DATASET\\Training Dataset\\934.png',
 'E:\\EYE DATASET\\Training Dataset\\1142.png',
 'E:\\EYE DATASET\\Training Dataset\\1662.png',
 'E:\\EYE DATASET\\Training Dataset\\1568.png',
 'E:\\EYE DATASET\\Training Dataset\\143.png',
 'E:\\EYE DATASET\\Training Dataset\\1331.png',
 'E:\\EYE DATASET\\Training Dataset\\858.png',
 'E:\\EYE DATASET\\Training Dataset\\1629.png',
 'E:\\EYE DATASET\\Training Dataset\\658.png',
 'E:\\EYE DATASET\\Training Dataset\\1412.png',
 'E:\\EYE DATASET\\Training Dataset\\318.png',
 'E:\\EYE DATASET\\Training Dataset\\1069.png',
 'E:\\EYE DATASET\\Training Dataset\\1287',
 'E:\\EYE DATASET\\Training Dataset\\3.png',
 'E:\\EYE DATASET\\Training Dataset\\1446.png',
 'E:\\EYE DATASET\\Training Dataset\\1203.png',
 'E:\\EYE DATASET\\Training Dataset\\829.png',
 'E:\\EYE DATASET\\Training Dataset\\1120.png',
 'E:\\EYE DATASET\\Training Dataset\\1377.png',
 'E:\\EYE DATASET\\Training Dataset\\85.png',
 'E:\\EYE DATASET\\Training Dataset\\264.png',
 'E:\\EYE DATASET\\Training Dataset\\215.png',
 'E:\\EYE DATASET\\Training Dataset\\1089.png',
 'E:\\EYE DATASET\\Training Dataset\\689',
 'E:\\EYE DATASET\\Training Dataset\\1247.png',
 'E:\\EYE DATASET\\Training Dataset\\949.png',
 'E:\\EYE DATASET\\Training Dataset\\1208.png',
 'E:\\EYE DATASET\\Training Dataset\\1556',
 'E:\\EYE DATASET\\Training Dataset\\341.png',
 'E:\\EYE DATASET\\Training Dataset\\1501.png',
 'E:\\EYE DATASET\\Training Dataset\\1580',
 'E:\\EYE DATASET\\Training Dataset\\219.png',
 'E:\\EYE DATASET\\Training Dataset\\1040.png',
 'E:\\EYE DATASET\\Training Dataset\\1158.png',
 'E:\\EYE DATASET\\Training Dataset\\1269',
 'E:\\EYE DATASET\\Training Dataset\\102.png',
 'E:\\EYE DATASET\\Training Dataset\\1636.png',
 'E:\\EYE DATASET\\Training Dataset\\379.png',
 'E:\\EYE DATASET\\Training Dataset\\1569.png',
 'E:\\EYE DATASET\\Training Dataset\\157.png',
 'E:\\EYE DATASET\\Training Dataset\\1296.png',
 'E:\\EYE DATASET\\Training Dataset\\1218',
 'E:\\EYE DATASET\\Training Dataset\\933.png',
 'E:\\EYE DATASET\\Training Dataset\\308.png',
 'E:\\EYE DATASET\\Training Dataset\\1649.png',
 'E:\\EYE DATASET\\Training Dataset\\134.png',
 'E:\\EYE DATASET\\Training Dataset\\878',
 'E:\\EYE DATASET\\Training Dataset\\119.png',
 'E:\\EYE DATASET\\Training Dataset\\590.png',
 'E:\\EYE DATASET\\Training Dataset\\526',
 'E:\\EYE DATASET\\Training Dataset\\1643.png',
 'E:\\EYE DATASET\\Training Dataset\\1540',
 'E:\\EYE DATASET\\Training Dataset\\938.png',
 'E:\\EYE DATASET\\Training Dataset\\1638.png',
 'E:\\EYE DATASET\\Training Dataset\\1599',
 'E:\\EYE DATASET\\Training Dataset\\465.png',
 'E:\\EYE DATASET\\Training Dataset\\1359.png',
 'E:\\EYE DATASET\\Training Dataset\\1175.png',
 'E:\\EYE DATASET\\Training Dataset\\1323.png',
 'E:\\EYE DATASET\\Training Dataset\\1627.png',
 'E:\\EYE DATASET\\Training Dataset\\1141.png',
 'E:\\EYE DATASET\\Training Dataset\\1608.png',
 'E:\\EYE DATASET\\Training Dataset\\1538.png',
 'E:\\EYE DATASET\\Training Dataset\\25',
 'E:\\EYE DATASET\\Training Dataset\\1681.png',
 'E:\\EYE DATASET\\Training Dataset\\750.png',
 'E:\\EYE DATASET\\Training Dataset\\161.png',
 'E:\\EYE DATASET\\Training Dataset\\539.png',
 'E:\\EYE DATASET\\Training Dataset\\1170.png',
 'E:\\EYE DATASET\\Training Dataset\\1276.png',
 'E:\\EYE DATASET\\Training Dataset\\1090.png',
 'E:\\EYE DATASET\\Training Dataset\\1567.png',
 'E:\\EYE DATASET\\Training Dataset\\105.png',
 'E:\\EYE DATASET\\Training Dataset\\484.png',
 'E:\\EYE DATASET\\Training Dataset\\461',
 'E:\\EYE DATASET\\Training Dataset\\1030.png',
 'E:\\EYE DATASET\\Training Dataset\\225.png',
 'E:\\EYE DATASET\\Training Dataset\\43.png',
 'E:\\EYE DATASET\\Training Dataset\\36.png',
 'E:\\EYE DATASET\\Training Dataset\\1094.png',
 'E:\\EYE DATASET\\Training Dataset\\142',
 'E:\\EYE DATASET\\Training Dataset\\706.png',
 'E:\\EYE DATASET\\Training Dataset\\1592',
 'E:\\EYE DATASET\\Training Dataset\\284.png',
 'E:\\EYE DATASET\\Training Dataset\\1646.png',
 'E:\\EYE DATASET\\Training Dataset\\527.png',
 'E:\\EYE DATASET\\Training Dataset\\659.png',
 'E:\\EYE DATASET\\Training Dataset\\1522.png',
 'E:\\EYE DATASET\\Training Dataset\\976.png',
 'E:\\EYE DATASET\\Training Dataset\\212.png',
 'E:\\EYE DATASET\\Training Dataset\\1347.png',
 'E:\\EYE DATASET\\Training Dataset\\70.png',
 'E:\\EYE DATASET\\Training Dataset\\97.png',
 'E:\\EYE DATASET\\Training Dataset\\1348.png',
 'E:\\EYE DATASET\\Training Dataset\\1066.png',
 'E:\\EYE DATASET\\Training Dataset\\1650.png',
 'E:\\EYE DATASET\\Training Dataset\\545.png',
 'E:\\EYE DATASET\\Training Dataset\\418.png',
 'E:\\EYE DATASET\\Training Dataset\\107.png',
 'E:\\EYE DATASET\\Training Dataset\\1521.png',
 'E:\\EYE DATASET\\Training Dataset\\1383.png',
 'E:\\EYE DATASET\\Training Dataset\\596.png',
 'E:\\EYE DATASET\\Training Dataset\\242.png',
 'E:\\EYE DATASET\\Training Dataset\\1418.png',
 'E:\\EYE DATASET\\Training Dataset\\252.png',
 'E:\\EYE DATASET\\Training Dataset\\755',
 'E:\\EYE DATASET\\Training Dataset\\1116.png',
 'E:\\EYE DATASET\\Training Dataset\\731',
 'E:\\EYE DATASET\\Training Dataset\\463.png',
 'E:\\EYE DATASET\\Training Dataset\\561.png',
 'E:\\EYE DATASET\\Training Dataset\\202.png',
 'E:\\EYE DATASET\\Training Dataset\\771.png',
 'E:\\EYE DATASET\\Training Dataset\\1519.png',
 'E:\\EYE DATASET\\Training Dataset\\510.png',
 'E:\\EYE DATASET\\Training Dataset\\280.png',
 'E:\\EYE DATASET\\Training Dataset\\1020.png',
 'E:\\EYE DATASET\\Training Dataset\\1308.png',
 'E:\\EYE DATASET\\Training Dataset\\1207.png',
 'E:\\EYE DATASET\\Training Dataset\\1201.png',
 'E:\\EYE DATASET\\Training Dataset\\1166.png',
 'E:\\EYE DATASET\\Training Dataset\\1258.png',
 'E:\\EYE DATASET\\Training Dataset\\1259.png',
 'E:\\EYE DATASET\\Training Dataset\\751.png',
 'E:\\EYE DATASET\\Training Dataset\\1563.png',
 'E:\\EYE DATASET\\Training Dataset\\1605',
 'E:\\EYE DATASET\\Training Dataset\\71.png',
 'E:\\EYE DATASET\\Training Dataset\\1515.png',
 'E:\\EYE DATASET\\Training Dataset\\1851.png',
 'E:\\EYE DATASET\\Training Dataset\\1328',
 'E:\\EYE DATASET\\Training Dataset\\1668.png',
 'E:\\EYE DATASET\\Training Dataset\\586.png',
 'E:\\EYE DATASET\\Training Dataset\\170.png',
 'E:\\EYE DATASET\\Training Dataset\\1191',
 'E:\\EYE DATASET\\Training Dataset\\1093.png',
 'E:\\EYE DATASET\\Training Dataset\\1693.png',
 'E:\\EYE DATASET\\Training Dataset\\1277.png',
 'E:\\EYE DATASET\\Training Dataset\\1195.png',
 'E:\\EYE DATASET\\Training Dataset\\231.png',
 'E:\\EYE DATASET\\Training Dataset\\1251.png',
 'E:\\EYE DATASET\\Training Dataset\\1180.png',
 'E:\\EYE DATASET\\Training Dataset\\1384.png',
 'E:\\EYE DATASET\\Training Dataset\\565.png',
 'E:\\EYE DATASET\\Training Dataset\\1079.png',
 'E:\\EYE DATASET\\Training Dataset\\411.png',
 'E:\\EYE DATASET\\Training Dataset\\506.png',
 'E:\\EYE DATASET\\Training Dataset\\1356.png',
 'E:\\EYE DATASET\\Training Dataset\\1252.png',
 'E:\\EYE DATASET\\Training Dataset\\705.png',
 'E:\\EYE DATASET\\Training Dataset\\1557',
 'E:\\EYE DATASET\\Training Dataset\\1031.png']

In [49]:
for i in range(len(paths)):
    if '.png' not in paths[i]:
        paths[i] = paths[i] + '.png'

In [50]:
y2 = []
for i in df_combined1.labels:
    if(i=='ARMD'):
        y2.append(1)
    elif(i=='Myopia'):
        y2.append(2)
    elif(i=='DR'):
        y2.append(3)
y2 = np.array(y2)
y2

array([3, 3, 3, 3, 3, 3, 2, 2, 3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 2, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3,
       3, 1, 3, 1, 3, 1, 3, 3, 2, 3, 3, 3, 1, 2, 1, 2, 3, 3, 3, 3, 2, 3,
       3, 3, 2, 3, 1, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2,
       3, 2, 3, 3, 3, 2, 3, 3, 2, 3, 1, 1, 3, 2, 1, 3, 3, 3, 3, 2, 2, 3,
       2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 2, 2, 3, 3, 2, 3, 3, 3, 3, 3, 3,
       2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 1, 3, 3, 3, 3, 3, 2, 3, 3, 3, 2,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 1, 3, 3, 3, 3, 1, 1, 3, 3, 3,
       3, 2, 3, 3, 3, 3, 2, 3, 3, 2, 2, 2, 3, 1, 3, 3, 3, 2, 3, 3, 3, 3,
       2, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 2, 2, 3, 2, 3, 3, 3, 3, 2, 1, 3,
       3, 3, 1, 2, 2, 1, 3, 3, 3, 1, 3, 3, 3, 3, 2, 3, 1, 2, 3, 3, 3, 1,
       3, 3, 1, 3, 1, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 2, 2, 3, 2,
       3, 3, 2, 3, 2, 1, 2, 2, 3, 3, 2, 1, 3, 1, 3, 3, 3, 3, 3, 3, 2, 3,
       3, 3, 3, 3, 3, 2, 2, 2, 2, 3, 3, 3, 3, 3, 1, 2, 1, 3, 3, 3, 2, 3,
       2, 3, 2, 3, 3, 3, 3, 3, 2, 2, 3, 1, 3, 3, 2, 1, 3, 3, 3, 1, 3, 3,
       3, 3, 3, 3, 3, 3, 2, 3, 2, 2, 3, 3, 3, 1, 2])

### Loading and Combining the previous dataset.

In [51]:
df

,ID,Patient Age,Patient Sex,Left-Fundus,Right-Fundus,Left-Diagnostic Keywords,Right-Diagnostic Keywords,N,D,G,C,A,H,M,O,filepath,labels,target,filename
0,0,69,Female,0_left.jpg,0_right.jpg,cataract,normal fundus,0,0,0,1,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['N'],"[1, 0, 0, 0, 0, 0, 0, 0]",0_right.jpg
1,1,57,Male,1_left.jpg,1_right.jpg,normal fundus,normal fundus,1,0,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['N'],"[1, 0, 0, 0, 0, 0, 0, 0]",1_right.jpg
2,2,42,Male,2_left.jpg,2_right.jpg,laser spotï¼Œmoderate non proliferative retinopathy,moderate non proliferative retinopathy,0,1,0,0,0,0,0,1,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",2_right.jpg
3,4,53,Male,4_left.jpg,4_right.jpg,macular epiretinal membrane,mild nonproliferative retinopathy,0,1,0,0,0,0,0,1,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4_right.jpg
4,5,50,Female,5_left.jpg,5_right.jpg,moderate non proliferative retinopathy,moderate non proliferative retinopathy,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",5_right.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6387,4686,63,Male,4686_left.jpg,4686_right.jpg,severe nonproliferative retinopathy,proliferative diabetic retinopathy,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4686_left.jpg
6388,4688,42,Male,4688_left.jpg,4688_right.jpg,moderate non proliferative retinopathy,moderate non proliferative retinopathy,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4688_left.jpg
6389,4689,54,Male,4689_left.jpg,4689_right.jpg,mild nonproliferative retinopathy,normal fundus,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4689_left.jpg
6390,4690,57,Male,4690_left.jpg,4690_right.jpg,mild nonproliferative retinopathy,mild nonproliferative retinopathy,0,1,0,0,0,0,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['D'],"[0, 1, 0, 0, 0, 0, 0, 0]",4690_left.jpg
6391,4784,58,Male,4784_left.jpg,4784_right.jpg,hypertensive retinopathyï¼Œage-related macular d...,hypertensive retinopathyï¼Œage-related macular d...,0,0,0,0,1,1,0,0,../input/ocular-disease-recognition-odir5k/ODI...,['H'],"[0, 0, 0, 0, 0, 1, 0, 0]",4784_left.jpg

In [52]:
img_dir2 = r'E:\EYE DATASET\preprocessed_images'

In [53]:
df = df.iloc[:,1:7]
df.head()

,Patient Age,Patient Sex,Left-Fundus,Right-Fundus,Left-Diagnostic Keywords,Right-Diagnostic Keywords
0,69,Female,0_left.jpg,0_right.jpg,cataract,normal fundus
1,57,Male,1_left.jpg,1_right.jpg,normal fundus,normal fundus
2,42,Male,2_left.jpg,2_right.jpg,laser spotï¼Œmoderate non proliferative retinopathy,moderate non proliferative retinopathy
3,53,Male,4_left.jpg,4_right.jpg,macular epiretinal membrane,mild nonproliferative retinopathy
4,50,Female,5_left.jpg,5_right.jpg,moderate non proliferative retinopathy,moderate non proliferative retinopathy

In [54]:
s1 = df['Left-Diagnostic Keywords']
s1.head()

0                                             cataract
1                                        normal fundus
2    laser spotï¼Œmoderate non proliferative retinopathy
3                          macular epiretinal membrane
4               moderate non proliferative retinopathy
Name: Left-Diagnostic Keywords, dtype: object

In [55]:
s2 = df['Right-Diagnostic Keywords']
s2.head()

0                             normal fundus
1                             normal fundus
2    moderate non proliferative retinopathy
3         mild nonproliferative retinopathy
4    moderate non proliferative retinopathy
Name: Right-Diagnostic Keywords, dtype: object

In [56]:
for i in range(6392):
    if 'age-related' in s1[i]:
        s1[i] = 'ARMD'
    if 'cataract' in s1[i]:
        s1[i] = 'Cataract'
    if 'pathological myopia' in s1[i]:
        s1[i] = 'Myopia'
    if 'normal' in s1[i]:
        s1[i] = 'Normal'
    if 'glaucoma' in s1[i]:
        s1[i] = 'Glaucoma'
    if 'hypertensive' in s1[i]:
        s1[i] = 'Hypertension'
    if 'diabetic' in s1[i]:
        s1[i] = 'Diabetic Retinopathy'

<ipython-input-56-5342e86ddb25>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1[i] = 'Cataract'
<ipython-input-56-5342e86ddb25>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1[i] = 'Normal'
<ipython-input-56-5342e86ddb25>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1[i] = 'Hypertension'
<ipython-input-56-5342e86ddb25>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1[i] = 'Myopia'
<ipython-input-56-5342e86ddb25>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1[i] = 'ARMD'
<ipython-input-56-5342e86ddb25>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1[i] = 'Diabetic Retinopathy'
<ipython-input-56-5342e86ddb25>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1[i] = 'Glaucoma'

In [57]:
df_left_arm = df[df['Left-Diagnostic Keywords'] == 'ARMD']
df_left_arm.head()

,Patient Age,Patient Sex,Left-Fundus,Right-Fundus,Left-Diagnostic Keywords,Right-Diagnostic Keywords
34,35,Male,43_left.jpg,43_right.jpg,ARMD,dry age-related macular degenerationï¼Œglaucoma
39,69,Female,48_left.jpg,48_right.jpg,ARMD,dry age-related macular degeneration
44,65,Female,53_left.jpg,53_right.jpg,ARMD,dry age-related macular degeneration
46,62,Male,55_left.jpg,55_right.jpg,ARMD,dry age-related macular degeneration
85,73,Female,102_left.jpg,102_right.jpg,ARMD,dry age-related macular degeneration

In [58]:
for i in range(6392):
    if 'age-related' in s2[i]:
        s2[i] = 'ARMD'
    if 'cataract' in s2[i]:
        s2[i] = 'Cataract'
    if 'pathological myopia' in s2[i]:
        s2[i] = 'Myopia'
    if 'normal' in s2[i]:
        s2[i] = 'Normal'
    if 'glaucoma' in s2[i]:
        s2[i] = 'Glaucoma'
    if 'hypertensive' in s2[i]:
        s2[i] = 'Hypertension'
    if 'diabetic' in s2[i]:
        s2[i] = 'Diabetic Retinopathy'

<ipython-input-58-a172d0bd1bc4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2[i] = 'Normal'
<ipython-input-58-a172d0bd1bc4>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2[i] = 'Hypertension'
<ipython-input-58-a172d0bd1bc4>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2[i] = 'Myopia'
<ipython-input-58-a172d0bd1bc4>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2[i] = 'Cataract'
<ipython-input-58-a172d0bd1bc4>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2[i] = 'ARMD'
<ipython-input-58-a172d0bd1bc4>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2[i] = 'Diabetic Retinopathy'
<ipython-input-58-a172d0bd1bc4>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2[i] = 'Glaucoma'

In [59]:
df_rt_arm = df[df['Right-Diagnostic Keywords'] == 'ARMD']
df_rt_arm.head()

,Patient Age,Patient Sex,Left-Fundus,Right-Fundus,Left-Diagnostic Keywords,Right-Diagnostic Keywords
34,35,Male,43_left.jpg,43_right.jpg,ARMD,ARMD
39,69,Female,48_left.jpg,48_right.jpg,ARMD,ARMD
44,65,Female,53_left.jpg,53_right.jpg,ARMD,ARMD
46,62,Male,55_left.jpg,55_right.jpg,ARMD,ARMD
57,56,Female,71_left.jpg,71_right.jpg,Diabetic Retinopathy,ARMD

In [60]:
df_arm_filenames = df_left_arm['Left-Fundus'].append(df_rt_arm['Right-Fundus'], ignore_index=True)
df_arm_filenames.head()

0     43_left.jpg
1     48_left.jpg
2     53_left.jpg
3     55_left.jpg
4    102_left.jpg
dtype: object

In [61]:
df_left_nor = df[df['Left-Diagnostic Keywords'] == 'Normal']
df_left_nor.head()

,Patient Age,Patient Sex,Left-Fundus,Right-Fundus,Left-Diagnostic Keywords,Right-Diagnostic Keywords
1,57,Male,1_left.jpg,1_right.jpg,Normal,Normal
7,59,Male,8_left.jpg,8_right.jpg,Normal,Normal
8,54,Male,9_left.jpg,9_right.jpg,Normal,vitreous degeneration
12,55,Male,14_left.jpg,14_right.jpg,Normal,macular epiretinal membrane
13,50,Male,15_left.jpg,15_right.jpg,Normal,myelinated nerve fibers

In [62]:
df_rt_nor = df[df['Right-Diagnostic Keywords'] == 'Normal']
df_rt_nor.head()

,Patient Age,Patient Sex,Left-Fundus,Right-Fundus,Left-Diagnostic Keywords,Right-Diagnostic Keywords
0,69,Female,0_left.jpg,0_right.jpg,Cataract,Normal
1,57,Male,1_left.jpg,1_right.jpg,Normal,Normal
7,59,Male,8_left.jpg,8_right.jpg,Normal,Normal
9,70,Male,10_left.jpg,10_right.jpg,epiretinal membrane,Normal
21,63,Female,26_left.jpg,26_right.jpg,moderate non proliferative retinopathy,Normal

In [63]:
df_nor_filenames = df_left_nor['Left-Fundus'].append(df_rt_nor['Right-Fundus'],ignore_index=True)
df_nor_filenames

0           1_left.jpg
1           8_left.jpg
2           9_left.jpg
3          14_left.jpg
4          15_left.jpg
             ...
5678    4644_right.jpg
5679    4659_right.jpg
5680    4660_right.jpg
5681    4671_right.jpg
5682    4689_right.jpg
Length: 5683, dtype: object

In [64]:
len(df_nor_filenames)

5683

In [65]:
df_left_myo = df[df['Left-Diagnostic Keywords'] == 'Myopia']
df_left_myo.head()

,Patient Age,Patient Sex,Left-Fundus,Right-Fundus,Left-Diagnostic Keywords,Right-Diagnostic Keywords
11,60,Female,13_left.jpg,13_right.jpg,Myopia,Myopia
16,58,Male,18_left.jpg,18_right.jpg,Myopia,Myopia
29,68,Female,35_left.jpg,35_right.jpg,Myopia,Normal
88,57,Female,106_left.jpg,106_right.jpg,Myopia,Myopia
122,49,Female,144_left.jpg,144_right.jpg,Myopia,Normal

In [66]:
df_rt_myo = df[df['Right-Diagnostic Keywords'] == 'Myopia']
df_rt_myo.head()

,Patient Age,Patient Sex,Left-Fundus,Right-Fundus,Left-Diagnostic Keywords,Right-Diagnostic Keywords
11,60,Female,13_left.jpg,13_right.jpg,Myopia,Myopia
14,54,Female,16_left.jpg,16_right.jpg,Normal,Myopia
16,58,Male,18_left.jpg,18_right.jpg,Myopia,Myopia
37,66,Male,46_left.jpg,46_right.jpg,moderate non proliferative retinopathy,Myopia
45,66,Female,54_left.jpg,54_right.jpg,Normal,Myopia

In [67]:
df_myo_filenames = df_left_myo['Left-Fundus'].append(df_rt_myo['Right-Fundus'],ignore_index=True)
df_myo_filenames

0         13_left.jpg
1         18_left.jpg
2         35_left.jpg
3        106_left.jpg
4        144_left.jpg
            ...
452    1681_right.jpg
453    1686_right.jpg
454    1694_right.jpg
455    1718_right.jpg
456    1971_right.jpg
Length: 457, dtype: object

In [68]:
df_left_drp = df[df['Left-Diagnostic Keywords'] == 'Diabetic Retinopathy']
df_left_drp.head()

,Patient Age,Patient Sex,Left-Fundus,Right-Fundus,Left-Diagnostic Keywords,Right-Diagnostic Keywords
52,80,Male,64_left.jpg,64_right.jpg,Diabetic Retinopathy,Diabetic Retinopathy
55,56,Male,67_left.jpg,67_right.jpg,Diabetic Retinopathy,Diabetic Retinopathy
57,56,Female,71_left.jpg,71_right.jpg,Diabetic Retinopathy,ARMD
90,54,Female,108_left.jpg,108_right.jpg,Diabetic Retinopathy,Normal
160,55,Female,188_left.jpg,188_right.jpg,Diabetic Retinopathy,Cataract

In [69]:
df_rt_drp = df[df['Right-Diagnostic Keywords'] == 'Diabetic Retinopathy']
df_rt_drp.head()

,Patient Age,Patient Sex,Left-Fundus,Right-Fundus,Left-Diagnostic Keywords,Right-Diagnostic Keywords
52,80,Male,64_left.jpg,64_right.jpg,Diabetic Retinopathy,Diabetic Retinopathy
55,56,Male,67_left.jpg,67_right.jpg,Diabetic Retinopathy,Diabetic Retinopathy
201,54,Male,234_left.jpg,234_right.jpg,Diabetic Retinopathy,Diabetic Retinopathy
213,64,Male,249_left.jpg,249_right.jpg,moderate non proliferative retinopathy,Diabetic Retinopathy
231,49,Female,268_left.jpg,268_right.jpg,moderate non proliferative retinopathyï¼Œlaser spot,Diabetic Retinopathy

In [70]:
df_drp_filenames = df_left_drp['Left-Fundus'].append(df_rt_drp['Right-Fundus'],ignore_index=True)
df_drp_filenames

0        64_left.jpg
1        67_left.jpg
2        71_left.jpg
3       108_left.jpg
4       188_left.jpg
           ...
86    4131_right.jpg
87    4391_right.jpg
88    4624_right.jpg
89    4631_right.jpg
90    4686_right.jpg
Length: 91, dtype: object

In [71]:
df_nor_filenames = pd.DataFrame(df_nor_filenames, columns = ["filename"])
df_nor_filenames["label"] = "Normal"
df_nor_filenames.head()

      filename   label
0   1_left.jpg  Normal
1   8_left.jpg  Normal
2   9_left.jpg  Normal
3  14_left.jpg  Normal
4  15_left.jpg  Normal

In [72]:
df_myo_filenames = pd.DataFrame(df_myo_filenames, columns = ["filename"])
df_myo_filenames["label"] = "Myopia"
df_myo_filenames.head()

       filename   label
0   13_left.jpg  Myopia
1   18_left.jpg  Myopia
2   35_left.jpg  Myopia
3  106_left.jpg  Myopia
4  144_left.jpg  Myopia

In [73]:
df_drp_filenames = pd.DataFrame(df_drp_filenames, columns = ["filename"])
df_drp_filenames["label"] = "Diabetic_Retinopathy"
df_drp_filenames.head()

       filename                 label
0   64_left.jpg  Diabetic_Retinopathy
1   67_left.jpg  Diabetic_Retinopathy
2   71_left.jpg  Diabetic_Retinopathy
3  108_left.jpg  Diabetic_Retinopathy
4  188_left.jpg  Diabetic_Retinopathy

In [74]:
df_arm_filenames = pd.DataFrame(df_arm_filenames, columns = ["filename"])
df_arm_filenames["label"] = "ARMD"
df_arm_filenames.head()

       filename label
0   43_left.jpg  ARMD
1   48_left.jpg  ARMD
2   53_left.jpg  ARMD
3   55_left.jpg  ARMD
4  102_left.jpg  ARMD

In [75]:
len(df_arm_filenames)

551

In [76]:
df_nor_filenames = df_nor_filenames.sample(600)
len(df_nor_filenames)

600

In [77]:
len(df_drp_filenames)

91

In [78]:
len(df_myo_filenames)

457

In [79]:
print(len(ARMD))
print(len(MYA))
print(len(DR))

34
71
240

In [80]:
print(f"ARMD = {34+551}")
print(f"MYA = {71+457}")
print(f"DR = {240+91}")
print(f"NOR = {600}")

ARMD = 585
MYA = 528
DR = 331
NOR = 600

In [81]:
df_combined = df_arm_filenames.append([df_nor_filenames,df_drp_filenames,df_myo_filenames],ignore_index = True)
df_combined

            filename   label
0        43_left.jpg    ARMD
1        48_left.jpg    ARMD
2        53_left.jpg    ARMD
3        55_left.jpg    ARMD
4       102_left.jpg    ARMD
...              ...     ...
1694  1681_right.jpg  Myopia
1695  1686_right.jpg  Myopia
1696  1694_right.jpg  Myopia
1697  1718_right.jpg  Myopia
1698  1971_right.jpg  Myopia

[1699 rows x 2 columns]

In [82]:
df_combined = df_combined.sample(1699)
df_combined = df_combined.reset_index(drop=True)
df_combined

            filename                 label
0      2407_left.jpg                Normal
1      1607_left.jpg                Myopia
2     1881_right.jpg                  ARMD
3      4279_left.jpg  Diabetic_Retinopathy
4     1529_right.jpg                Myopia
...              ...                   ...
1694  2743_right.jpg                Normal
1695  4330_right.jpg                  ARMD
1696   4279_left.jpg  Diabetic_Retinopathy
1697  3431_right.jpg                Normal
1698  2699_right.jpg                Normal

[1699 rows x 2 columns]

In [83]:
a  = np.array(df_combined.filename)

In [84]:
path1 = []
type(path1)

list

In [85]:
for i in range(1699):
    img = a[i]
    image = os.path.join(img_dir2, img)
    path1.append(image)

In [86]:
len(path1)

1699

In [87]:
path1

['E:\\EYE DATASET\\preprocessed_images\\2407_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1607_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1881_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\4279_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1529_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3181_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3394_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\934_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1876_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\504_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2799_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\893_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2625_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\4294_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1859_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\888_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1111_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2819_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1559_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\886_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1620_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1663_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1520_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\997_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1543_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1845_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\153_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3293_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\908_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1546_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1103_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\237_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1196_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2635_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\4527_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\10_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1558_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2699_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1547_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\4512_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1829_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\419_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1536_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1879_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1536_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1836_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1873_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\688_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\927_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2469_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1561_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1588_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1098_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1881_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1874_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3156_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\35_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\608_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1570_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1564_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2713_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1613_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\82_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1881_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1146_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1579_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\43_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2825_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3034_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\13_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\191_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1557_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3979_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2645_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\4131_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1872_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1191_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1893_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1836_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\719_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1605_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2340_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1531_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\934_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\864_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1731_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1561_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3043_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1942_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\719_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2611_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\377_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2171_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1603_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2963_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2361_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\13_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3288_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\238_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\982_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1104_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\642_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1617_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3388_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1558_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2454_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1588_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\608_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\184_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\334_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\998_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\126_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\48_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2994_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\53_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1563_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1545_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1527_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2770_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1549_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1593_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\164_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\410_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\564_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1831_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3332_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\235_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\758_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\642_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1091_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1561_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\213_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\424_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\178_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1836_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1840_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1064_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1388_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2910_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1853_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1559_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3207_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\311_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2385_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\152_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2603_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1547_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\334_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3430_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1621_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3096_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\722_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1547_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1314_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1889_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1612_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1686_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\722_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3139_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\662_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1850_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\513_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1566_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\410_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1879_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2967_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\771_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\265_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1893_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\125_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2883_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\737_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1563_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3077_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\264_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1605_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2569_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\559_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3008_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\136_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1600_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\831_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\530_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2864_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2696_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\961_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\567_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1613_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1544_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\992_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2749_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1710_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\608_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2361_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3130_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1838_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2418_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2746_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3222_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1829_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\4322_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1556_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\603_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1674_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2794_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3417_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3318_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1799_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3348_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\815_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1847_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2065_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1593_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1584_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\781_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1544_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1093_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\210_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3236_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\168_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3012_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1240_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2338_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\572_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2932_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\885_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2511_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3395_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2964_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\48_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\547_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1295_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\4131_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\315_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1878_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\681_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1452_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\615_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3000_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1476_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2888_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1541_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3397_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2544_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\513_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1580_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1614_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\855_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1021_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\212_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1530_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\91_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1831_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\652_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\4459_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3260_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1841_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1578_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2996_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\514_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3291_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\540_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1886_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1519_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\514_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\788_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2938_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3028_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1043_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\514_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2458_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\4491_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1528_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\603_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2748_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2553_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1526_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1427_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1550_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1197_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1629_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\319_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1569_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2554_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1458_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1666_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1612_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1835_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1572_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\410_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3424_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2483_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2604_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\598_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2906_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\390_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1125_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2682_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1534_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3382_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\712_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2357_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1590_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\233_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3341_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\69_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\265_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\455_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3433_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\542_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\808_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2622_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1551_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1971_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\4068_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1196_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1612_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1550_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\977_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1559_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2748_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\102_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1644_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2966_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1535_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\712_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\178_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2882_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2566_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\919_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3350_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\46_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2382_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1666_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\46_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1845_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1548_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3439_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1554_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1830_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1533_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\247_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1718_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\172_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2900_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2514_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\3234_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1877_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\2950_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\4068_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1602_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\610_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\234_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\598_right.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\1647_left.jpg',
 'E:\\EYE DATASET\\preprocessed_images\\852_right.jpg',

In [88]:
y1 = []
for i in df_combined.label:
    if(i=='Normal'):
        y1.append(0)
    elif(i=='ARMD'):
        y1.append(1)
    elif(i=='Myopia'):
        y1.append(2)
    elif(i=='Diabetic_Retinopathy'):
        y1.append(3)
y1 = np.array(y1)
y1

array([0, 2, 1, ..., 3, 0, 0])

In [89]:
len(y1)

1699

In [90]:
paths = np.concatenate((path1,paths))

In [91]:
paths

array(['E:\\EYE DATASET\\preprocessed_images\\2407_left.jpg',
       'E:\\EYE DATASET\\preprocessed_images\\1607_left.jpg',
       'E:\\EYE DATASET\\preprocessed_images\\1881_right.jpg', ...,
       'E:\\EYE DATASET\\Training Dataset\\705.png',
       'E:\\EYE DATASET\\Training Dataset\\1557.png',
       'E:\\EYE DATASET\\Training Dataset\\1031.png'], dtype='<U49')

In [92]:
y = np.concatenate((y1,y2))

In [99]:
data = []
for i in range(2044):
    img = paths[i]
    image = cv2.imread(img)
    image = cv2.resize(image,(224,224))
    data.append(image)

In [100]:
data = np.array(data)

In [101]:
data = data/255

In [102]:
x = data

In [103]:
print(len(x))
len(y)

2044

2044

## MobileNet V2 Model

In [104]:
import numpy as np
import cv2

import PIL.Image as Image
import os

import matplotlib.pylab as plt

import tensorflow as tf
import tensorflow_hub as hub

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

In [105]:
feature_extractor_model = "https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4"

pretrained_model_without_top_layer = hub.KerasLayer(
    feature_extractor_model, input_shape=(224, 224, 3), trainable=False)

In [106]:
num_of_classes = 4

model = tf.keras.Sequential([
  pretrained_model_without_top_layer,
  tf.keras.layers.Dense(num_of_classes)
])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
keras_layer (KerasLayer)     (None, 1280)              2257984
_________________________________________________________________
dense (Dense)                (None, 4)                 5124
=================================================================
Total params: 2,263,108
Trainable params: 5,124
Non-trainable params: 2,257,984
_________________________________________________________________

In [108]:
model.compile(
  optimizer="adam",
  loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
  metrics=['accuracy'])

model.fit(x, y, epochs=20)

Epoch 1/20
64/64 [==============================] - 53s 788ms/step - loss: 0.2345 - accuracy: 0.9281
Epoch 2/20
64/64 [==============================] - 51s 799ms/step - loss: 0.2194 - accuracy: 0.9369
Epoch 3/20
64/64 [==============================] - 51s 803ms/step - loss: 0.2093 - accuracy: 0.9442
Epoch 4/20
64/64 [==============================] - 51s 801ms/step - loss: 0.2064 - accuracy: 0.9428
Epoch 5/20
64/64 [==============================] - 51s 802ms/step - loss: 0.1940 - accuracy: 0.9467
Epoch 6/20
64/64 [==============================] - 51s 802ms/step - loss: 0.1881 - accuracy: 0.9535
Epoch 7/20
64/64 [==============================] - 52s 809ms/step - loss: 0.1856 - accuracy: 0.9501
Epoch 8/20
64/64 [==============================] - 52s 808ms/step - loss: 0.1783 - accuracy: 0.9550
Epoch 9/20
64/64 [==============================] - 52s 807ms/step - loss: 0.1675 - accuracy: 0.9643
Epoch 10/20
64/64 [==============================] - 52s 810ms/step - loss: 0.1665 - accuracy: 0.9560
Epoch 11/20
64/64 [==============================] - 52s 807ms/step - loss: 0.1614 - accuracy: 0.9599
Epoch 12/20
64/64 [==============================] - 51s 804ms/step - loss: 0.1547 - accuracy: 0.9682
Epoch 13/20
64/64 [==============================] - 51s 802ms/step - loss: 0.1531 - accuracy: 0.9662
Epoch 14/20
64/64 [==============================] - 52s 812ms/step - loss: 0.1448 - accuracy: 0.9692
Epoch 15/20
64/64 [==============================] - 53s 824ms/step - loss: 0.1391 - accuracy: 0.9741
Epoch 16/20
64/64 [==============================] - 46s 724ms/step - loss: 0.1378 - accuracy: 0.9697
Epoch 17/20
64/64 [==============================] - 46s 715ms/step - loss: 0.1326 - accuracy: 0.9726
Epoch 18/20
64/64 [==============================] - 46s 713ms/step - loss: 0.1281 - accuracy: 0.9770
Epoch 19/20
64/64 [==============================] - 46s 715ms/step - loss: 0.1238 - accuracy: 0.9790
Epoch 20/20
64/64 [==============================] - 46s 713ms/step - loss: 0.1255 - accuracy: 0.9750

In [112]:
from keras.models import save_model

In [117]:
model.save("my_model")

INFO:tensorflow:Assets written to: my_model\assets

INFO:tensorflow:Assets written to: my_model\assets

In [119]:
m1 = load_model("my_model")

In [132]:
img_dir = r'E:\EYE DATASET\Test Dataset\Test Dataset'

In [133]:
df3 = pd.read_csv(r"E:\EYE DATASET\Test Dataset\RFMiD_Testing_Labels.csv")

In [134]:
df3

,ID,Disease_Risk,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
0,1,1,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
636,637,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
637,638,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
638,639,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
639,640,1,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [135]:
df3 = df3[df3['Disease_Risk'] == 1]
df3

,ID,Disease_Risk,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
0,1,1,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
636,637,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
637,638,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
638,639,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
639,640,1,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [136]:
df3 = df3.iloc[:,:7]
df3

      ID  Disease_Risk  DR  ARMD  MH  DN  MYA
0      1             1   1     0   0   0    0
1      2             1   1     0   0   0    0
2      3             1   1     0   0   0    0
3      4             1   0     0   0   0    0
4      5             1   0     0   0   0    0
..   ...           ...  ..   ...  ..  ..  ...
635  636             1   0     0   0   0    1
636  637             1   0     0   0   0    1
637  638             1   0     0   0   0    0
638  639             1   0     0   0   0    0
639  640             1   0     1   0   0    1

[506 rows x 7 columns]

In [137]:
df3 = df3.reset_index(drop = True)

In [138]:
x = []
for i in range(len(df3)):
    x.append(str(df3['ID'][i]))

In [139]:
for i in range(len(df3)):
    x[i] = x[i] + '.png'

In [140]:
df3['ID'] = x

In [141]:
df3.drop(columns = ['MH','DN'],inplace=True)

In [142]:
df3

          ID  Disease_Risk  DR  ARMD  MYA
0      1.png             1   1     0    0
1      2.png             1   1     0    0
2      3.png             1   1     0    0
3      4.png             1   0     0    0
4      5.png             1   0     0    0
..       ...           ...  ..   ...  ...
501  636.png             1   0     0    1
502  637.png             1   0     0    1
503  638.png             1   0     0    0
504  639.png             1   0     0    0
505  640.png             1   0     1    1

[506 rows x 5 columns]

In [143]:
x = df3[df3['DR'] == 1]
x = x['ID']
x

0        1.png
1        2.png
2        3.png
8        9.png
9       10.png
        ...
445    506.png
446    507.png
453    528.png
454    534.png
468    560.png
Name: ID, Length: 124, dtype: object

In [144]:
df_DR_filenames = pd.DataFrame()

In [145]:
df_DR_filenames['filenames'] = x

In [146]:
df_DR_filenames['labels'] = 'DR'

In [147]:
df_DR_filenames = df_DR_filenames.reset_index(drop = True)
df_DR_filenames

    filenames labels
0       1.png     DR
1       2.png     DR
2       3.png     DR
3       9.png     DR
4      10.png     DR
..        ...    ...
119   506.png     DR
120   507.png     DR
121   528.png     DR
122   534.png     DR
123   560.png     DR

[124 rows x 2 columns]

In [148]:
x = df3[df3['MYA'] == 1]
x = x['ID']
x

47      48.png
77      78.png
78      79.png
79      80.png
86      87.png
97      98.png
105    106.png
106    107.png
109    110.png
156    157.png
187    188.png
222    223.png
251    253.png
252    254.png
277    287.png
278    288.png
323    344.png
324    345.png
325    346.png
326    347.png
378    406.png
385    414.png
388    418.png
389    419.png
400    431.png
402    433.png
462    545.png
486    607.png
500    635.png
501    636.png
502    637.png
505    640.png
Name: ID, dtype: object

In [149]:
df_MYA_filenames = pd.DataFrame()

In [150]:
df_MYA_filenames['filenames'] = x
df_MYA_filenames['label'] = 'Myopia'

In [151]:
df_MYA_filenames = df_MYA_filenames.reset_index(drop = True)
df_MYA_filenames

   filenames   label
0     48.png  Myopia
1     78.png  Myopia
2     79.png  Myopia
3     80.png  Myopia
4     87.png  Myopia
5     98.png  Myopia
6    106.png  Myopia
7    107.png  Myopia
8    110.png  Myopia
9    157.png  Myopia
10   188.png  Myopia
11   223.png  Myopia
12   253.png  Myopia
13   254.png  Myopia
14   287.png  Myopia
15   288.png  Myopia
16   344.png  Myopia
17   345.png  Myopia
18   346.png  Myopia
19   347.png  Myopia
20   406.png  Myopia
21   414.png  Myopia
22   418.png  Myopia
23   419.png  Myopia
24   431.png  Myopia
25   433.png  Myopia
26   545.png  Myopia
27   607.png  Myopia
28   635.png  Myopia
29   636.png  Myopia
30   637.png  Myopia
31   640.png  Myopia

In [152]:
x = df3[df3['ARMD'] == 1]
x = x['ID']
x

11      12.png
37      38.png
38      39.png
42      43.png
43      44.png
44      45.png
45      46.png
47      48.png
48      49.png
50      51.png
51      52.png
56      57.png
58      59.png
66      67.png
88      89.png
109    110.png
121    122.png
151    152.png
187    188.png
188    189.png
242    243.png
308    328.png
322    343.png
411    449.png
417    457.png
418    458.png
420    465.png
421    466.png
447    508.png
451    514.png
505    640.png
Name: ID, dtype: object

In [153]:
df_ARMD_filenames = pd.DataFrame()
df_ARMD_filenames['filenames'] = x
df_ARMD_filenames['labels'] = 'ARMD'
df_ARMD_filenames = df_ARMD_filenames.reset_index(drop = True)
df_ARMD_filenames

   filenames labels
0     12.png   ARMD
1     38.png   ARMD
2     39.png   ARMD
3     43.png   ARMD
4     44.png   ARMD
5     45.png   ARMD
6     46.png   ARMD
7     48.png   ARMD
8     49.png   ARMD
9     51.png   ARMD
10    52.png   ARMD
11    57.png   ARMD
12    59.png   ARMD
13    67.png   ARMD
14    89.png   ARMD
15   110.png   ARMD
16   122.png   ARMD
17   152.png   ARMD
18   188.png   ARMD
19   189.png   ARMD
20   243.png   ARMD
21   328.png   ARMD
22   343.png   ARMD
23   449.png   ARMD
24   457.png   ARMD
25   458.png   ARMD
26   465.png   ARMD
27   466.png   ARMD
28   508.png   ARMD
29   514.png   ARMD
30   640.png   ARMD

In [154]:
df3 = df3[df3['Disease_Risk'] == 0]

In [155]:
df3.reset_index(drop=True,inplace=True)

In [156]:
x = []
for i in range(len(df3)):
    x.append(str(df3['ID'][i]))

In [157]:
for i in range(len(x)): 
    x[i] = x[i] + '.png'

In [158]:
df3['ID'] = x

In [159]:
df3 = df3['ID']

In [160]:
df3['labels'] = 'Normal'

C:\Users\KIIT\anaconda3\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\KIIT\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3343: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

In [161]:
df_Nor_filenames = pd.DataFrame()
df_Nor_filenames['filenames'] = x

In [162]:
df_Nor_filenames['labels'] = 'Normal'
df_Nor_filenames

Empty DataFrame
Columns: [filenames, labels]
Index: []

In [163]:
df_MYA_filenames.drop(columns = 'label',inplace = True)
df_MYA_filenames['labels'] = 'Myopia'

In [164]:
df_MYA_filenames

   filenames  labels
0     48.png  Myopia
1     78.png  Myopia
2     79.png  Myopia
3     80.png  Myopia
4     87.png  Myopia
5     98.png  Myopia
6    106.png  Myopia
7    107.png  Myopia
8    110.png  Myopia
9    157.png  Myopia
10   188.png  Myopia
11   223.png  Myopia
12   253.png  Myopia
13   254.png  Myopia
14   287.png  Myopia
15   288.png  Myopia
16   344.png  Myopia
17   345.png  Myopia
18   346.png  Myopia
19   347.png  Myopia
20   406.png  Myopia
21   414.png  Myopia
22   418.png  Myopia
23   419.png  Myopia
24   431.png  Myopia
25   433.png  Myopia
26   545.png  Myopia
27   607.png  Myopia
28   635.png  Myopia
29   636.png  Myopia
30   637.png  Myopia
31   640.png  Myopia

In [165]:
df_DR_filenames

    filenames labels
0       1.png     DR
1       2.png     DR
2       3.png     DR
3       9.png     DR
4      10.png     DR
..        ...    ...
119   506.png     DR
120   507.png     DR
121   528.png     DR
122   534.png     DR
123   560.png     DR

[124 rows x 2 columns]

In [166]:
df_ARMD_filenames

   filenames labels
0     12.png   ARMD
1     38.png   ARMD
2     39.png   ARMD
3     43.png   ARMD
4     44.png   ARMD
5     45.png   ARMD
6     46.png   ARMD
7     48.png   ARMD
8     49.png   ARMD
9     51.png   ARMD
10    52.png   ARMD
11    57.png   ARMD
12    59.png   ARMD
13    67.png   ARMD
14    89.png   ARMD
15   110.png   ARMD
16   122.png   ARMD
17   152.png   ARMD
18   188.png   ARMD
19   189.png   ARMD
20   243.png   ARMD
21   328.png   ARMD
22   343.png   ARMD
23   449.png   ARMD
24   457.png   ARMD
25   458.png   ARMD
26   465.png   ARMD
27   466.png   ARMD
28   508.png   ARMD
29   514.png   ARMD
30   640.png   ARMD

In [167]:
df_combined = df_DR_filenames.append([df_ARMD_filenames,df_Nor_filenames,df_MYA_filenames])

In [168]:
len(df_combined)

187

In [169]:
df_combined = df_combined.sample(187)

In [170]:
df_combined = df_combined.reset_index(drop = True)

In [171]:
a  = np.array(df_combined.filenames)
paths = []

In [172]:
for i in range(len(df_combined)):
    img = a[i]
    image = os.path.join(img_dir, img)
    paths.append(image)

In [173]:
paths

['E:\\EYE DATASET\\Test Dataset\\Test Dataset\\157.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\180.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\253.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\212.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\607.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\106.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\243.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\514.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\79.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\286.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\168.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\194.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\373.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\316.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\360.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\473.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\259.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\112.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\87.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\114.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\169.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\457.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\480.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\152.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\395.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\498.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\209.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\139.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\406.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\59.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\506.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\284.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\175.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\51.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\386.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\350.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\328.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\423.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\100.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\188.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\636.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\115.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\408.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\344.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\193.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\223.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\319.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\224.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\466.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\9.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\458.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\528.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\637.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\419.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\545.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\334.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\308.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\38.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\151.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\287.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\160.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\142.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\478.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\640.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\432.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\10.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\265.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\298.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\479.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\165.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\122.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\213.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\283.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\148.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\349.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\496.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\356.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\317.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\185.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\181.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\254.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\195.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\418.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\222.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\89.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\415.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\346.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\3.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\285.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\39.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\124.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\289.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\416.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\484.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\306.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\345.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\485.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\110.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\508.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\469.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\449.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\98.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\1.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\292.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\48.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\431.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\161.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\385.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\206.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\167.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\205.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\282.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\424.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\635.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\474.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\49.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\323.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\121.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\288.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\101.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\57.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\200.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\640.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\44.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\300.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\492.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\46.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\12.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\188.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\110.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\507.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\465.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\407.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\129.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\107.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\497.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\80.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\335.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\347.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\433.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\82.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\86.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\470.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\48.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\84.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\176.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\43.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\67.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\426.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\307.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\247.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\410.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\111.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\52.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\2.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\351.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\147.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\429.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\196.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\472.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\189.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\352.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\83.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\234.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\271.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\343.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\293.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\128.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\255.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\414.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\140.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\141.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\45.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\394.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\266.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\248.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\534.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\430.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\483.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\387.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\182.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\78.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\560.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\260.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\320.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\482.png',
 'E:\\EYE DATASET\\Test Dataset\\Test Dataset\\355.png']

In [174]:
y = []
for i in df_combined.labels:
    if(i=='Normal'):
        y.append(0)
    elif(i=='ARMD'):
        y.append(1)
    elif(i=='Myopia'):
        y.append(2)
    elif(i=='DR'):
        y.append(3)
y = np.array(y)
y

array([2, 3, 2, 3, 2, 2, 1, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 1,
       3, 1, 3, 3, 3, 3, 2, 1, 3, 3, 3, 1, 3, 3, 1, 3, 3, 1, 2, 3, 3, 2,
       3, 2, 3, 3, 1, 3, 1, 3, 2, 2, 2, 3, 3, 1, 3, 2, 3, 3, 3, 2, 3, 3,
       3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 1, 3, 2, 3,
       3, 1, 3, 3, 3, 3, 3, 2, 3, 1, 1, 3, 1, 2, 3, 3, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 2, 3, 1, 3, 3, 2, 3, 1, 3, 1, 1, 3, 3, 1, 1, 2, 2, 3, 1,
       3, 3, 2, 3, 2, 3, 2, 2, 3, 3, 3, 1, 3, 3, 1, 1, 3, 3, 3, 3, 3, 1,
       3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 1, 3, 3, 3, 2, 3, 3, 1, 3, 3, 3,
       3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3])

In [175]:
data = []
for i in range(len(df_combined)):
    img = paths[i]
    image = cv2.imread(img)
    image = cv2.resize(image,(224,224))
    data.append(image)

In [448]:
data = np.array(data)
data = data/255

In [453]:
x_test1 = data
y_test1 = y

In [452]:
model1.evaluate(x,y)

11/11 [==============================] - 4s 367ms/step - loss: 1.1968 - accuracy: 0.6417

[1.196793794631958, 0.6417445540428162]

In [455]:
len(x)

321

## ResNet 50

In [121]:
num_classes = 4
model2 = tf.keras.Sequential([
    hub.KerasLayer("https://tfhub.dev/tensorflow/resnet_50/classification/1",
                   trainable=False,input_shape=(224, 224, 3)),
    tf.keras.layers.Dense(num_classes, activation='softmax')
])

In [122]:
model2 = tf.keras.Sequential([
  pretrained_model_without_top_layer,
  tf.keras.layers.Dense(num_of_classes)
])

model2.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
keras_layer (KerasLayer)     (None, 1280)              2257984
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 5124
=================================================================
Total params: 2,263,108
Trainable params: 5,124
Non-trainable params: 2,257,984
_________________________________________________________________

In [124]:
model2.compile(
  optimizer="adam",
  loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
  metrics=['accuracy'])

model2.fit(x, y, epochs=20)

Epoch 1/20
64/64 [==============================] - 30s 445ms/step - loss: 0.2398 - accuracy: 0.9295
Epoch 2/20
64/64 [==============================] - 34s 528ms/step - loss: 0.2233 - accuracy: 0.9369
Epoch 3/20
64/64 [==============================] - 34s 534ms/step - loss: 0.2128 - accuracy: 0.9442
Epoch 4/20
64/64 [==============================] - 34s 529ms/step - loss: 0.2092 - accuracy: 0.9432
Epoch 5/20
64/64 [==============================] - 34s 527ms/step - loss: 0.2015 - accuracy: 0.9437
Epoch 6/20
64/64 [==============================] - 34s 531ms/step - loss: 0.1926 - accuracy: 0.9525
Epoch 7/20
64/64 [==============================] - 35s 540ms/step - loss: 0.1838 - accuracy: 0.9589
Epoch 8/20
64/64 [==============================] - 36s 569ms/step - loss: 0.1797 - accuracy: 0.9565
Epoch 9/20
64/64 [==============================] - 36s 558ms/step - loss: 0.1710 - accuracy: 0.9604
Epoch 10/20
64/64 [==============================] - 35s 549ms/step - loss: 0.1679 - accuracy: 0.9594
Epoch 11/20
64/64 [==============================] - 33s 509ms/step - loss: 0.1637 - accuracy: 0.9594
Epoch 12/20
64/64 [==============================] - 33s 517ms/step - loss: 0.1559 - accuracy: 0.9648
Epoch 13/20
64/64 [==============================] - 32s 501ms/step - loss: 0.1520 - accuracy: 0.9648
Epoch 14/20
64/64 [==============================] - 32s 503ms/step - loss: 0.1484 - accuracy: 0.9667
Epoch 15/20
64/64 [==============================] - 32s 507ms/step - loss: 0.1443 - accuracy: 0.9682
Epoch 16/20
64/64 [==============================] - 32s 496ms/step - loss: 0.1399 - accuracy: 0.9702
Epoch 17/20
64/64 [==============================] - 32s 498ms/step - loss: 0.1334 - accuracy: 0.9755
Epoch 18/20
64/64 [==============================] - 33s 511ms/step - loss: 0.1349 - accuracy: 0.9716
Epoch 19/20
64/64 [==============================] - 32s 493ms/step - loss: 0.1266 - accuracy: 0.9765
Epoch 20/20
64/64 [==============================] - 31s 492ms/step - loss: 0.1222 - accuracy: 0.9785

In [748]:
model2.evaluate(x_test1,y_test1)

11/11 [==============================] - 7s 510ms/step - loss: 1.3227 - accuracy: 0.6417

[1.3227204084396362, 0.6417445540428162]

In [125]:
model2.save("model2")

INFO:tensorflow:Assets written to: model2\assets

INFO:tensorflow:Assets written to: model2\assets